/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dd_ffmpeg_DDPlayer */

#ifndef _Included_com_dd_ffmpeg_DDPlayer
#define _Included_com_dd_ffmpeg_DDPlayer
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_dd_ffmpeg_DDPlayer_play
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
